name: "RAPCore"
on: ['pull_request']

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PUSH_DOCS: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:

    - uses: actions/checkout@v2
  
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: TinyFPGABX Flow
      run: nix-shell --arg docs false --arg prog false --command 'make build-full BOARD=tinyfpgabx'
    - name: ULX3S Flow
      run: nix-shell --arg docs false --arg prog false --command 'make build-full BOARD=ulx3s'
    - name: RAPBo Flow
      run: nix-shell --arg docs false --arg prog false --command 'make build-full BOARD=rapbo'
    - name: ECP5 Eval Flow
      run: nix-shell --arg docs false --arg prog false --command 'make build-full BOARD=ecp5evn'
    - name: IVerilog Compat
      run: nix-shell --arg docs false --arg prog false --command 'make iverilog-parse'
    - name: reg initialization
      run: ./etc/reginit.sh
    - name: RAPcore-cli
      run: make rapcore-cli
    - name: Build Docs
      run: nix-shell --arg prog false --command 'make docs-html'

    # Upload bitstreams, support software, and documentation
    - uses: actions/upload-artifact@v2
      with:
        name: RAPcores Build
        path: |
          ./build/*.bit
          ./logs
          ./rapcore-cli
          ./docs/_build/html

    # publish documentation changes if on main branch
    - name: Commit documentation changes
      if: env.PUSH_DOCS
      run: |
        git clone https://github.com/rapcores/rapcores.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      if: env.PUSH_DOCS
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}