name: "RAPCore"
on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
  
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: TinyFPGABX Flow
      run: nix-shell --command 'make build-full -j4 BOARD=tinyfpgabx'
    - name: ULX3S Flow
      run: nix-shell --command 'make build-full -j4 BOARD=ulx3s'
    - name: RAPBo Flow
      run: nix-shell --command 'make build-full -j4 BOARD=rapbo'
    - name: ECP5 Eval Flow
      run: nix-shell --command 'make build-full -j4 BOARD=ecp5evn'
    - name: reg initialization
      run: ./etc/reginit.sh

    - uses: actions/upload-artifact@v2
      with:
        name: RAPcores Build
        path: |
          ./build/*.bit
          ./logs
