name: "RAPCore"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: TinyFPGABX Flow
      run: nix-shell --command 'make BOARD=tinyfpgabx'
    - name: ULX3S Flow
      run: nix-shell --command 'make BOARD=ulx3s'
    - name: RAPBo Flow
      run: nix-shell --command 'make BOARD=rapbo'
    - name: Formal Verification
      run: nix-shell --command 'make formal'
    - name: iverilog parse compat
      run: nix-shell --command 'make iverilog-parse'
