name: "RAPCore"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: TinyFPGABX Flow  
      run: nix-shell --command 'make BOARD=tinyfpgabx'
    - name: Formal Verification
      run: nix-shell --command 'make formal BOARD=tinyfpgabx'
