name: "RAPCore"
on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
  
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: TinyFPGABX Flow
      run: nix-shell --arg docs false --arg prog false --command 'make build-full BOARD=tinyfpgabx'
    - name: ULX3S Flow
      run: nix-shell --arg docs false --arg prog false --command 'make build-full BOARD=ulx3s'
    - name: RAPBo Flow
      run: nix-shell --arg docs false --arg prog false --command 'make build-full BOARD=rapbo'
    - name: ECP5 Eval Flow
      run: nix-shell --arg docs false --arg prog false --command 'make build-full BOARD=ecp5evn'
    - name: IVerilog Compat
      run: nix-shell --arg docs false --arg prog false --command 'make iverilog-parse'
    - name: reg initialization
      run: ./etc/reginit.sh
    - name: RAPcore-cli
      run: make rapcore-cli
    - name: Build Docs
      run: nix-shell --arg prog false --command 'make docs-html'

    - uses: actions/upload-artifact@v2
      with:
        name: RAPcores Build
        path: |
          ./build/*.bit
          ./logs
          ./rapcore-cli
          ./docs/_build/html

